// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeH6jdfM442x4x3cpeM--bdLt2weTz70U',
    appId: '1:106892369498:web:b398602bbe7c0d23634263',
    messagingSenderId: '106892369498',
    projectId: 'kavach-37bfd',
    authDomain: 'kavach-37bfd.firebaseapp.com',
    storageBucket: 'kavach-37bfd.appspot.com',
    measurementId: 'G-R5WCC46Y14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIY69Tz1ZAaoK0gV9UsOg9RCmLI8Dsxg8',
    appId: '1:106892369498:android:6b9365a34282c12a634263',
    messagingSenderId: '106892369498',
    projectId: 'kavach-37bfd',
    storageBucket: 'kavach-37bfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiMqpn2XuApDMxKCEefI-t8c_e5SRSTbg',
    appId: '1:106892369498:ios:d8cb83729f03e188634263',
    messagingSenderId: '106892369498',
    projectId: 'kavach-37bfd',
    storageBucket: 'kavach-37bfd.appspot.com',
    iosBundleId: 'com.example.kavach',
  );
}
